services:
  goweb:
    image: ghcr.io/bilusteknoloji/toolstack.app/toolstack.app:latest
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"

      # middlewares
      - "traefik.http.middlewares.ibankeeper-addprefix.addprefix.prefix=/ibankeeper"
      - "traefik.http.middlewares.iptool-addprefix.addprefix.prefix=/ip"
      - "traefik.http.middlewares.reminder-addprefix.addprefix.prefix=/reminder"

      # custom http response headers
      - "traefik.http.middlewares.toolstackapp-headers.headers.customresponseheaders.X-Last-Deploy=${LAST_DEPLOY}"

      # toolstack.app (https)
      - "traefik.http.routers.toolstackapp.rule=Host(`toolstack.app`) || Host(`www.toolstack.app`)"
      - "traefik.http.routers.toolstackapp.entrypoints=websecure"
      - "traefik.http.routers.toolstackapp.tls=true"
      - "traefik.http.routers.toolstackapp.tls.certresolver=bilusorg"
      - "traefik.http.routers.toolstackapp.middlewares=infra_gitsha_header,infra_version_header,cache_headers,toolstackapp-headers"
      - "traefik.http.routers.toolstackapp.service=toolstackapp-service"
      - "traefik.http.services.toolstackapp-service.loadbalancer.server.port=8000"

      # toolstack.app (http -> https)
      - "traefik.http.routers.toolstackapp-insecure.rule=Host(`toolstack.app`) || Host(`www.toolstack.app`)"
      - "traefik.http.routers.toolstackapp-insecure.entrypoints=web"
      - "traefik.http.routers.toolstackapp-insecure.middlewares=redirecttohttps"

      # ibankeeper.toolstack.app (https)
      - "traefik.http.routers.ibankeeper.rule=Host(`ibankeeper.toolstack.app`)"
      - "traefik.http.routers.ibankeeper.entrypoints=websecure"
      - "traefik.http.routers.ibankeeper.tls=true"
      - "traefik.http.routers.ibankeeper.tls.certresolver=bilusorg"
      - "traefik.http.routers.ibankeeper.middlewares=infra_gitsha_header,infra_version_header,cache_headers,ibankeeper-addprefix,toolstackapp-headers"
      - "traefik.http.routers.ibankeeper.service=toolstackapp-service"

      # reminder.toolstack.app (https)
      - "traefik.http.routers.reminder.rule=Host(`reminder.toolstack.app`)"
      - "traefik.http.routers.reminder.entrypoints=websecure"
      - "traefik.http.routers.reminder.tls=true"
      - "traefik.http.routers.reminder.tls.certresolver=bilusorg"
      - "traefik.http.routers.reminder.middlewares=infra_gitsha_header,infra_version_header,cache_headers,reminder-addprefix,toolstackapp-headers"
      - "traefik.http.routers.reminder.service=toolstackapp-service"

      # ip.toolstack.app (https)
      # whatismyip.toolstack.app
      - "traefik.http.routers.iptool.rule=Host(`ip.toolstack.app`) || Host(`whatismyip.toolstack.app`)"
      - "traefik.http.routers.iptool.entrypoints=websecure"
      - "traefik.http.routers.iptool.tls=true"
      - "traefik.http.routers.iptool.tls.certresolver=bilusorg"
      - "traefik.http.routers.iptool.middlewares=infra_gitsha_header,infra_version_header,cache_headers,iptool-addprefix,toolstackapp-headers"
      - "traefik.http.routers.iptool.service=toolstackapp-service"

      # ip.toolstack.app (http for curl, httpie)
      # whatismyip.toolstack.app
      - "traefik.http.routers.iptool-insecure.rule=Host(`ip.toolstack.app`) || Host(`whatismyip.toolstack.app`)"
      - "traefik.http.routers.iptool-insecure.entrypoints=web"
      - "traefik.http.routers.iptool-insecure.middlewares=iptool-addprefix"
      - "traefik.http.routers.iptool-insecure.service=toolstackapp-service"

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/healthz || exit 1"]
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
    ulimits:
      nproc: 4096
      nofile:
        soft: 10240
        hard: 10240
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: 64MB
        limits:
          cpus: "0.3"
          memory: 128MB

networks:
  traefik_net:
    external: true
